image: hiroyukionaka/pandoc-lualatex-ja

pipelines:
  default:
      - step:
          script:
            - rm -rf target
            - mkdir -p target
            - bash ./build.sh
            - bash ./deploy.sh master
  branches:
    release:
      - step:
          script:
            - rm -rf target
            - mkdir -p target
            - bash ./build.sh
            - bash ./deploy.sh release 
